### ISSUE TITLE
20页$urlRouterProvider.state()的用法

### ISSUE THREAD

**Issue by ltyely** [ng-nice/book#2]
安装fj并create项目，按照20页的步骤修改router.js后，访问页面控制台报错：

>  Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
> TypeError: $urlRouterProvider.state is not a function
>     at http://localhost:5000/configs/router.js:27:22

查了下ui router的[api](http://angular-ui.github.io/ui-router/site/#/api/ui.router.router.$urlRouterProvider)
，没有state这个方法。查看官网的sampleapp里也都是用$stateProvider进行路由定义，把router.js里所有$urlRouterProvider.state()改成$statProvider.state()后就不再报错。

**Comment by asnowwolf** [comment]
笔误，已添加勘误。
谢谢指正。
